### ISSUE TITLE
cannot get status for jobs with a dash in job ID

### ISSUE THREAD

**Issue by VascoVisser** [hashicorp/nomad#3141]
### Nomad version
Nomad v0.6.1
Nomad v0.6.2

### Operating system and Environment details
Linux 4.4.0-62-generic #83-Ubuntu SMP x86_64 GNU/Linux

### Issue
Starting from nomad 0.6.1 I am not able to get the status for a job via the cli if that job has a dash in its name.

### Reproduction steps
- download nomad 0.6.1 or 0.6.2
- start nomad: `nomad agent -dev` without any additional config
- run `nomad status foo-bar`

output:
``` 
Error querying search with id: "Unexpected response code: 500 (alloc lookup failed: index error: Input (without hyphens) must be even length)"
```
expected output (the same as when querying for a job ID without a dash):
```
Unable to resolve ID: "foo-bar"
```

### Nomad Server logs (if appropriate)
```
    2017/08/31 00:15:40.243520 [ERR] http: Request /v1/search, error: alloc lookup failed: index error: Input (without hyphens) must be even length
    2017/08/31 00:15:40.244141 [DEBUG] http: Request /v1/search (818.813µs)
```

**Comment by dadgar** [comment]
Hey this has been fixed and will be out in 0.6.3. In the meantime please use `nomad job status`

**Comment by fho** [comment]
@dadgar the problem still happens with nomad 0.6.3.

```
[root@sb-fho-643 (screen) ~] nomad -v                                                                                                                                        
Nomad v0.6.3                                                                                                                                                                 
[root@sb-fho-643 (screen) ~] nomad status arregistry-service                                                                                                                 
Error querying search with id: "Unexpected response code: 500 (alloc lookup failed: index error: Input (without hyphens) must be even length)"                               
[root@sb-fho-643 (screen) ~] nomad status user-service  
Error querying search with id: "Unexpected response code: 500 (alloc lookup failed: index error: Input (without hyphens) must be even length)"                               
```

**Comment by dadgar** [comment]
@fho Sorry about that. Added tests to cover all possible values and have fixed this.

**Comment by metroidprototype** [comment]
I'm still seeing this in both 0.6.3 and 0.7.0-beta:

```
[rampal@latveria bin]$ nomad -v
Nomad v0.6.3
[rampal@latveria bin]$ nomad status splunk-forwarder
Error querying search with id: "Unexpected response code: 404 (404 page not found\n)"
[rampal@latveria bin]$ nomad -v
Nomad v0.7.0-beta1
[rampal@latveria bin]$ nomad status splunk-forwarder
Error querying search with id: "Unexpected response code: 404 (404 page not found\n)"
[rampal@latveria bin]$
```

Rolling my binary back to 0.5.6 works fine.

**Comment by dadgar** [comment]
@metroidprototype I believe you may have just upgraded the CLI binary and not the servers/clients as well. I just tried with the job name you gave on 0.7.0-beta1 and it worked correctly.
