### ISSUE TITLE
interpolation does not work for destination in artifact stanza

### ISSUE THREAD

**Issue by Fuco1** [hashicorp/nomad#6929]
Copy of now closed #2752 

> ### Nomad version
> Nomad v0.9.5
> 
> ### Operating system and Environment details
> CentOS Linux release 7.3.1611 (Core)
> 
> ### Issue
> interpolation does not work in artifact { destination = "_**destination**_" } stanza
> 
> ### Reproduction steps
> create job with example from "[Job file section](#Job-file)"
> 
> [`nomad validate` and `nomad run` executes with no errors](#Nomad-Server-logs).
> 
> [`nomad status -verbose example` shows that download has been completed and task started](#Nomad-Client-logs)
> but as you can see from logs, task is terminated because, in my case, start script expected to be in _**/tmp/example-job/start.sh**_
> 
> Checking content of allocation on node that was assigned to run a task:
> 
> ```
> ls your_nomad_allocation_dir
> 
> ...
> ...
> drwxr-xr-x   3 root   root      17 Jun 28 13:08 ${NOMAD_META_DESTINATION_DIR}
> ...
> ```
> 
> ### Nomad Server logs
> ```
> $ nomad validate example.nomad
> Job validation successful
> ```
> 
> ### Nomad Client logs
> ```
> 06/28/17 13:08:44 PDT  Restarting             Task restarting in 27.305774574s
> 06/28/17 13:08:44 PDT  Terminated             Exit Code: 1
> 06/28/17 13:08:44 PDT  Started                Task started by client
> 06/28/17 13:08:26 PDT  Downloading Artifacts  Client is downloading artifacts
> ```
> 
> ### Job file
> ```
> job "example" {
> .....
>   meta {
>      DESTINATION_DIR = "/tmp/example-job"
>      SOURCE_URL = "https://example_url/example.tar.gz"
>   }
> ....
>   task "task" {
> ....
>      artifact {
>         source = "${NOMAD_META_SOURCE_URL}"
>         destination = "${NOMAD_META_DESTINATION_DIR}"
>      }
> .....
> }
> ```

**Comment by tgross** [comment]
Thanks for re-creating this one, @Fuco1. I noticed you changed the version to 0.9.5 from the original issue; are you experiencing this problem with 0.9.5?

**Comment by Fuco1** [comment]
@tgross yes indeed, I'm using 0.9.5.  My OS is also different (ubuntu 16.04 if I'm not mistaken) but that shouldn't play a big role.  But if necessary I can check exact build when I get to the office.

**Comment by 02strich** [comment]
I don't think this is supported at this point. Looking at https://github.com/hashicorp/nomad/blob/master/client/allocrunner/taskrunner/getter/getter.go#L100 the destination is taken as is and never interpolated. @tgross do you think this should be working already?

**Comment by Fuco1** [comment]
@stale this is still an issue

**Comment by kung-foo** [comment]
Still an issue with `Nomad v0.11.3 (8918fc804a0c6758b6e3e9960e4eb2e605e38552)`
